
-- 002.sql
-- t01_class, t02_schedule, t03_teacher, t05_manager
USE swp391_db_release;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS t01_class;
CREATE TABLE t01_class (
   C01_CLASS_ID INT AUTO_INCREMENT PRIMARY KEY,
   C01_CLASS_NAME VARCHAR(50) NOT NULL,
   C01_CLASS_CODE INT NOT NULL UNIQUE,
   C01_CLASS_DESC TEXT NOT NULL,
   C01_CLASS_START_DATE DATE NOT NULL,
   C01_CLASS_END_DATE DATE NOT NULL,
   C01_AMOUNT_OF_STUDENTS INT NOT NULL,
   C01_CLASS_FEE FLOAT NOT NULL,
   C01_CENTER_ID INT NOT NULL,
   C01_SUBJECT_ID INT NOT NULL,
   CONSTRAINT T01_CK_DATE CHECK (C01_CLASS_END_DATE >= C01_CLASS_START_DATE),
   CONSTRAINT FK_CLASS_CENTER FOREIGN KEY (C01_CENTER_ID) REFERENCES t04_center(C04_CENTER_ID),
   CONSTRAINT FK_CLASS_SUBJECT FOREIGN KEY (C01_SUBJECT_ID) REFERENCES t13_subject(C13_SUBJECT_ID)
);

DROP TABLE IF EXISTS t03_teacher;
CREATE TABLE t03_teacher (
     C03_TEACHER_ID INT AUTO_INCREMENT PRIMARY KEY,
     C03_CENTER_ID INT NOT NULL,
     C03_USER_ID INT NOT NULL,
     CONSTRAINT FK_TEACHER_CENTER FOREIGN KEY (C03_CENTER_ID) REFERENCES t04_center(C04_CENTER_ID),
     CONSTRAINT FK_TEACHER_USER FOREIGN KEY (C03_USER_ID) REFERENCES t14_user(C14_USER_ID)
);

DROP TABLE IF EXISTS t05_manager;
CREATE TABLE t05_manager (
     C05_MANAGER_ID INT AUTO_INCREMENT PRIMARY KEY,
     C05_CENTER_ID INT NOT NULL,
     C05_USER_ID INT NOT NULL,
     CONSTRAINT FK_MANAGER_CENTER FOREIGN KEY (C05_CENTER_ID) REFERENCES t04_center(C04_CENTER_ID),
     CONSTRAINT FK_MANAGER_USER FOREIGN KEY (C05_USER_ID) REFERENCES t14_user(C14_USER_ID)
);
   
DROP TABLE IF EXISTS t02_schedule;
CREATE TABLE t02_schedule (
    C02_SCHEDULE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C02_SCHEDULE_ROOM VARCHAR(20) NOT NULL,
    C02_SCHEDULE_DATE DATE NOT NULL,
    C02_SCHEDULE_START_TIME TIME NOT NULL,
    C02_SCHEDULE_END_TIME TIME NOT NULL,
    C02_CLASS_ID INT NOT NULL,
    C02_TEACHER_ID INT NOT NULL,
    C02_SUBJECT_ID INT NOT NULL,
    CONSTRAINT T02_CK_TIME CHECK (C02_SCHEDULE_END_TIME > C02_SCHEDULE_START_TIME),
    CONSTRAINT FK_SCHEDULE_CLASS FOREIGN KEY (C02_CLASS_ID) REFERENCES t01_class(C01_CLASS_ID),
    CONSTRAINT FK_SCHEDULE_TEACHER FOREIGN KEY (C02_TEACHER_ID) REFERENCES t03_teacher(C03_TEACHER_ID),
    CONSTRAINT FK_SCHEDULE_SUBJECT FOREIGN KEY (C02_SUBJECT_ID) REFERENCES t13_subject(C13_SUBJECT_ID)
);

SET FOREIGN_KEY_CHECKS = 1;