
-- 003.sql
-- t07_feedback, t08_material, t10_attendance, t11_result, t12_post
USE swp391_db_release;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS t07_feedback;
CREATE TABLE t07_feedback (
    C07_FEEDBACK_ID INT AUTO_INCREMENT PRIMARY KEY,
    C07_FEEDBACK_DESC TEXT NOT NULL,
    C07_FEEDBACK_TYPE BIT(1) NOT NULL,
    C07_USER_ID INT NOT NULL,
    C07_TEACHER_ID INT NOT NULL,
    CONSTRAINT FK_FEEDBACK_USER FOREIGN KEY (C07_USER_ID) REFERENCES t14_user(C14_USER_ID),
    CONSTRAINT FK_FEEDBACK_TEACHER FOREIGN KEY (C07_TEACHER_ID) REFERENCES t03_teacher(C03_TEACHER_ID)
);

DROP TABLE IF EXISTS t08_material;
CREATE TABLE t08_material (
    C08_MATERIALS_ID INT AUTO_INCREMENT PRIMARY KEY,
    C08_MATERIALS_NAME VARCHAR(100) NOT NULL,
    C08_TEACHER_ID INT NOT NULL,
    C08_SUBJECT_ID INT NOT NULL,
    CONSTRAINT FK_MATERIAL_TEACHER FOREIGN KEY (C08_TEACHER_ID) REFERENCES t03_teacher(C03_TEACHER_ID),
    CONSTRAINT FK_MATERIAL_SUBJECT FOREIGN KEY (C08_SUBJECT_ID) REFERENCES t13_subject(C13_SUBJECT_ID)
);

DROP TABLE IF EXISTS t10_attendance;
CREATE TABLE t10_attendance (
    C10_ATTENDANCE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C10_ATTENDANCE_STATUS BIT(1) NOT NULL,
    C10_USER_ID INT NOT NULL,
    C10_SCHEDULE_ID INT NOT NULL UNIQUE,
    CONSTRAINT FK_ATTENDANCE_USER FOREIGN KEY (C10_USER_ID) REFERENCES t14_user(C14_USER_ID),
    CONSTRAINT FK_ATTENDANCE_SCHEDULE FOREIGN KEY (C10_SCHEDULE_ID) REFERENCES t02_schedule(C02_SCHEDULE_ID)
);

DROP TABLE IF EXISTS t11_result;
CREATE TABLE t11_result (
    C11_RESULT_ID INT AUTO_INCREMENT PRIMARY KEY,
    C11_RESULT_TYPE INT NOT NULL, -- hệ số điểm: x1, x2, x3
    C11_RESULT_VAL INT NOT NULL,
    C11_USER_ID INT NOT NULL,
    C11_CLASS_ID INT NOT NULL,
    CONSTRAINT FK_RESULT_USER FOREIGN KEY (C11_USER_ID) REFERENCES t14_user(C14_USER_ID),
    CONSTRAINT FK_RESULT_CLASS FOREIGN KEY (C11_CLASS_ID) REFERENCES t01_class(C01_CLASS_ID)
);

DROP TABLE IF EXISTS t12_post;
CREATE TABLE t12_post (
    C12_POST_ID INT AUTO_INCREMENT PRIMARY KEY,
    C12_TITLE VARCHAR(100) NOT NULL,
    C12_CONTENT TEXT NOT NULL,
    C12_PUBLISHED_DATE DATE NOT NULL,
    C12_MANAGER_ID INT NOT NULL,
    C12_CENTER_ID INT NOT NULL,
    CONSTRAINT FK_POST_MANAGER FOREIGN KEY (C12_MANAGER_ID) REFERENCES t05_manager(C05_MANAGER_ID),
    CONSTRAINT FK_POST_CENTER FOREIGN KEY (C12_CENTER_ID) REFERENCES t04_center(C04_CENTER_ID)
);

SET FOREIGN_KEY_CHECKS = 1;




