-- CREATE DATABASE swp391_db_releasee;
USE swp391_db_releasee;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS t06_role;
CREATE TABLE t06_role (
   C06_ROLE_ID INT PRIMARY KEY,
   C06_ROLE_DESC ENUM('STUDENT', 'PARENT', 'TEACHER', 'MANAGER', 'ADMIN') NOT NULL
);

DROP TABLE IF EXISTS t14_user;
CREATE TABLE t14_user (
    C14_USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    C14_USER_USERNAME VARCHAR(30) NOT NULL UNIQUE,
    C14_USER_PASSWORD VARCHAR(50) NOT NULL,
    C14_ACC_STATUS BIT(1) NOT NULL,
    C14_USER_CODE INT NOT NULL UNIQUE,
    C14_USER_NAME VARCHAR(30) NOT NULL,
    C14_USER_PHONE VARCHAR(20) NOT NULL,
    C14_USER_ADDRESS VARCHAR(100) NOT NULL,
    C14_USER_DOB DATE NOT NULL,
    C14_USER_GENDER BIT(1) NOT NULL,
    C14_USER_EMAIL VARCHAR(50) NOT NULL,
    C14_ROLE_ID INT NOT NULL ,
    C14_PARENT_ID INT,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (C14_ROLE_ID) REFERENCES t06_role(C06_ROLE_ID),
    CONSTRAINT FK_USER_PARENT FOREIGN KEY (C14_PARENT_ID) REFERENCES t14_user(C14_USER_ID)
);

DROP TABLE IF EXISTS t09_image_avt;
CREATE TABLE t09_image_avt (
    C09_IMAGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C09_IMAGE_PATH VARCHAR(255) NOT NULL UNIQUE,
    C09_IMAGE_TYPE ENUM('STUDENT', 'PARENT', 'TEACHER', 'MANAGER', 'ADMIN', 'CENTER') NOT NULL,
    C09_USER_ID INT NOT NULL,
    CONSTRAINT FK_IMAGE_USER FOREIGN KEY (C09_USER_ID) REFERENCES t14_user(C14_USER_ID)
);

DROP TABLE IF EXISTS t13_subject;
CREATE TABLE t13_subject (
    C13_SUBJECT_ID INT AUTO_INCREMENT PRIMARY KEY,
    C13_SUBJECT_NAME VARCHAR(30) NOT NULL UNIQUE,
    C13_SUBJECT_DESC TEXT NOT NULL
);

DROP TABLE IF EXISTS t04_center;
CREATE TABLE t04_center (
    C04_CENTER_ID INT AUTO_INCREMENT PRIMARY KEY,
    C04_CENTER_CODE INT NOT NULL UNIQUE,
    C04_CENTER_NAME VARCHAR(30) NOT NULL,
    C04_CENTER_DESC TEXT NOT NULL,
    C04_CENTER_ADDRESS VARCHAR(50) NOT NULL,
    C04_CENTER_PHONE VARCHAR(20) NOT NULL,
    C04_CENTER_EMAIL VARCHAR(30) NOT NULL,
    C04_CENTER_REGULATIONS TEXT NOT NULL,
    C04_CREATED_AT DATE DEFAULT(CURRENT_TIMESTAMP) NOT NULL,
    C04_IMAGE_PATH TEXT NOT NULL
);


DROP TABLE IF EXISTS t01_class;
CREATE TABLE t01_class (
   C01_CLASS_ID INT AUTO_INCREMENT PRIMARY KEY,
   C01_CLASS_NAME VARCHAR(50) NOT NULL,
   C01_CLASS_CODE INT NOT NULL UNIQUE,
   C01_CLASS_DESC TEXT NOT NULL,
   C01_CLASS_START_DATE DATE NOT NULL,
   C01_CLASS_END_DATE DATE NOT NULL,
   C01_AMOUNT_OF_STUDENTS INT NOT NULL,
   C01_CLASS_FEE FLOAT NOT NULL,
   C01_CENTER_ID INT NOT NULL,
   C01_SUBJECT_ID INT NOT NULL,
   CONSTRAINT T01_CK_DATE CHECK (C01_CLASS_END_DATE >= C01_CLASS_START_DATE),
   CONSTRAINT FK_CLASS_CENTER FOREIGN KEY (C01_CENTER_ID) REFERENCES t04_center(C04_CENTER_ID),
   CONSTRAINT FK_CLASS_SUBJECT FOREIGN KEY (C01_SUBJECT_ID) REFERENCES t13_subject(C13_SUBJECT_ID)
);

DROP TABLE IF EXISTS t03_teacher;
CREATE TABLE t03_teacher (
     C03_TEACHER_ID INT AUTO_INCREMENT PRIMARY KEY,
     C03_CENTER_ID INT NOT NULL,
     C03_USER_ID INT NOT NULL,
     CONSTRAINT FK_TEACHER_CENTER FOREIGN KEY (C03_CENTER_ID) REFERENCES t04_center(C04_CENTER_ID),
     CONSTRAINT FK_TEACHER_USER FOREIGN KEY (C03_USER_ID) REFERENCES t14_user(C14_USER_ID)
);

DROP TABLE IF EXISTS t05_manager;
CREATE TABLE t05_manager (
     C05_MANAGER_ID INT AUTO_INCREMENT PRIMARY KEY,
     C05_CENTER_ID INT NOT NULL,
     C05_USER_ID INT NOT NULL,
     CONSTRAINT FK_MANAGER_CENTER FOREIGN KEY (C05_CENTER_ID) REFERENCES t04_center(C04_CENTER_ID),
     CONSTRAINT FK_MANAGER_USER FOREIGN KEY (C05_USER_ID) REFERENCES t14_user(C14_USER_ID)
);

DROP TABLE IF EXISTS t02_schedule;
CREATE TABLE t02_schedule (
    C02_SCHEDULE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C02_SCHEDULE_ROOM VARCHAR(20) NOT NULL,
    C02_SCHEDULE_DATE DATE NOT NULL,
    C02_SCHEDULE_START_TIME TIME NOT NULL,
    C02_SCHEDULE_END_TIME TIME NOT NULL,
    C02_CLASS_ID INT NOT NULL,
    C02_TEACHER_ID INT NOT NULL,
    C02_SUBJECT_ID INT NOT NULL,
    CONSTRAINT T02_CK_TIME CHECK (C02_SCHEDULE_END_TIME > C02_SCHEDULE_START_TIME),
    CONSTRAINT FK_SCHEDULE_CLASS FOREIGN KEY (C02_CLASS_ID) REFERENCES t01_class(C01_CLASS_ID),
    CONSTRAINT FK_SCHEDULE_TEACHER FOREIGN KEY (C02_TEACHER_ID) REFERENCES t03_teacher(C03_TEACHER_ID),
    CONSTRAINT FK_SCHEDULE_SUBJECT FOREIGN KEY (C02_SUBJECT_ID) REFERENCES t13_subject(C13_SUBJECT_ID)
);



DROP TABLE IF EXISTS t07_feedback;
CREATE TABLE t07_feedback (
    C07_FEEDBACK_ID INT AUTO_INCREMENT PRIMARY KEY,
    C07_FEEDBACK_DESC TEXT NOT NULL,
    C07_FEEDBACK_TYPE BIT(1) NOT NULL,
    C07_USER_ID INT NOT NULL,
    C07_TEACHER_ID INT NOT NULL,
    CONSTRAINT FK_FEEDBACK_USER FOREIGN KEY (C07_USER_ID) REFERENCES t14_user(C14_USER_ID),
    CONSTRAINT FK_FEEDBACK_TEACHER FOREIGN KEY (C07_TEACHER_ID) REFERENCES t03_teacher(C03_TEACHER_ID)
);

DROP TABLE IF EXISTS t08_material;
CREATE TABLE t08_material (
    C08_MATERIALS_ID INT AUTO_INCREMENT PRIMARY KEY,
    C08_MATERIALS_NAME VARCHAR(100) NOT NULL,
    C08_TEACHER_ID INT NOT NULL,
    C08_SUBJECT_ID INT NOT NULL,
    CONSTRAINT FK_MATERIAL_TEACHER FOREIGN KEY (C08_TEACHER_ID) REFERENCES t03_teacher(C03_TEACHER_ID),
    CONSTRAINT FK_MATERIAL_SUBJECT FOREIGN KEY (C08_SUBJECT_ID) REFERENCES t13_subject(C13_SUBJECT_ID)
);

DROP TABLE IF EXISTS t10_attendance;
CREATE TABLE t10_attendance (
    C10_ATTENDANCE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C10_ATTENDANCE_STATUS BIT(1) NOT NULL,
    C10_USER_ID INT NOT NULL,
    C10_SCHEDULE_ID INT NOT NULL UNIQUE,
    CONSTRAINT FK_ATTENDANCE_USER FOREIGN KEY (C10_USER_ID) REFERENCES t14_user(C14_USER_ID),
    CONSTRAINT FK_ATTENDANCE_SCHEDULE FOREIGN KEY (C10_SCHEDULE_ID) REFERENCES t02_schedule(C02_SCHEDULE_ID)
);

DROP TABLE IF EXISTS t11_result;
CREATE TABLE t11_result (
    C11_RESULT_ID INT AUTO_INCREMENT PRIMARY KEY,
    C11_RESULT_TYPE INT NOT NULL, -- hệ số điểm: x1, x2, x3
    C11_RESULT_VAL INT NOT NULL,
    C11_USER_ID INT NOT NULL,
    C11_CLASS_ID INT NOT NULL,
    CONSTRAINT FK_RESULT_USER FOREIGN KEY (C11_USER_ID) REFERENCES t14_user(C14_USER_ID),
    CONSTRAINT FK_RESULT_CLASS FOREIGN KEY (C11_CLASS_ID) REFERENCES t01_class(C01_CLASS_ID)
);

DROP TABLE IF EXISTS t12_post;
CREATE TABLE t12_post (
    C12_POST_ID INT AUTO_INCREMENT PRIMARY KEY,
    C12_TITLE VARCHAR(100) NOT NULL,
    C12_CONTENT TEXT NOT NULL,
    C12_PUBLISHED_DATE DATE NOT NULL,
    C12_MANAGER_ID INT NOT NULL,
    C12_CENTER_ID INT NOT NULL,
    CONSTRAINT FK_POST_MANAGER FOREIGN KEY (C12_MANAGER_ID) REFERENCES t05_manager(C05_MANAGER_ID),
    CONSTRAINT FK_POST_CENTER FOREIGN KEY (C12_CENTER_ID) REFERENCES t04_center(C04_CENTER_ID)
);


DROP TABLE IF EXISTS t15_enrollment; -- n-n: class - student
CREATE TABLE t15_enrollment (
     C15_ENROLLMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
     C15_USER_ID INT NOT NULL,
     C15_CLASS_ID INT NOT NULL,
     CONSTRAINT CK_T15_FK UNIQUE(C15_USER_ID, C15_CLASS_ID),
     CONSTRAINT FK_ENROLLMENT_USER FOREIGN KEY (C15_USER_ID) REFERENCES t14_user(C14_USER_ID),
     CONSTRAINT FK_ENROLLMENT_CLASS FOREIGN KEY (C15_CLASS_ID) REFERENCES t01_class(C01_CLASS_ID)
);

DROP TABLE IF EXISTS t16_user_center; -- n-n: center - student
CREATE TABLE t16_user_center (
     C16_USER_CENTER_ID INT AUTO_INCREMENT PRIMARY KEY,
     C16_USER_ID INT NOT NULL,
     C16_CENTER_ID INT NOT NULL,
     CONSTRAINT CK_T16_FK UNIQUE(C16_USER_ID, C16_CENTER_ID),
     CONSTRAINT FK_T16_USER FOREIGN KEY (C16_USER_ID) REFERENCES t14_user(C14_USER_ID),
     CONSTRAINT FK_T16_CENTER FOREIGN KEY (C16_CENTER_ID) REFERENCES t04_center(C04_CENTER_ID)
);

DROP TABLE IF EXISTS t17_student_schedule; -- n-n: 1 student học nhiều slot, 1 slot có nhiều student
CREATE TABLE t17_student_schedule (
     C17_STUDENT_SCHEDULE_ID INT AUTO_INCREMENT PRIMARY KEY,
     C17_USER_ID INT NOT NULL,
     C17_SCHEDULE_ID INT NOT NULL,
     CONSTRAINT CK_T17_FK UNIQUE(C17_USER_ID, C17_SCHEDULE_ID),
     CONSTRAINT FK_T17_USER FOREIGN KEY (C17_USER_ID) REFERENCES t14_user(C14_USER_ID),
     CONSTRAINT FK_T17_SCHEDULE FOREIGN KEY (C17_SCHEDULE_ID) REFERENCES t02_schedule(C02_SCHEDULE_ID)
);


SET FOREIGN_KEY_CHECKS = 1;